### ISSUE TITLE
当视频简介含有B站链接时会无法解析或解析错误

### ISSUE THREAD

**Issue by forchannot** [Well2333/nonebot-plugin-bilichat#119]
### 操作系统

Windows

### Python 版本

3.11

### NoneBot 版本

2.0.1

### Bilichat 版本

4.7.0

### 描述问题

当视频的简介中有可以解析的B站链接时，通过手机B站的分享为卡片形式会导致正则提取错误，解析到不正确的链接
在json的desc的值为简介，正则会将里面的内容错误提取
复现视频https://www.bilibili.com/video/av959100625

### 截图或日志

![Screenshot_2023-09-30-14-58-09-321_com microsoft rdc androidx](https://github.com/Well2333/nonebot-plugin-bilichat/assets/100580891/d7343429-a84b-4ff2-b47d-a347be2a6785)
![Screenshot_2023-09-30-14-58-22-133_com microsoft rdc androidx](https://github.com/Well2333/nonebot-plugin-bilichat/assets/100580891/78ba06dc-2aa0-48c4-a3a2-19aa1241de27)

**Comment by Well2333** [comment]
这个没有办法进一步区分，想不到好的解决方案

**Comment by Well2333** [comment]
此问题的出现原因是由于小程序或卡片包含了一部分简介，而正则表达式捕获了此部分内容，因此此问题仅存在于 QQ bot 的少数情况，而不是普遍状况。
如果需要分享，可以使用 **复制链接** 的方式发送，而不是小程序或卡片消息
