### ISSUE TITLE
Feature: 功能描述 添加对B站原生AI视频总结接口的支持

### ISSUE THREAD

**Issue by 23650** [Well2333/nonebot-plugin-bilichat#124]
### 希望能解决的问题

近期B站上线了“AI视频总结”的功能，入口位于B站网页版的视频页下方，点击后即可打开一个AI生成的总结页面
以下是对该入口的逻辑观察：

1. 该入口会固定出现在视频页的下方，与三连按钮在同一水平位置；
2. 视频的类型、发布时间、热门程度不影响入口的出现逻辑；
3. 视频的音频为音乐、无声、嘈杂时，该入口不可点击；
4. 多次请求后，该接口仍可用。

预测该接口的AI总结逻辑可能为调用字幕接口进行生成，且暂时没有请求限制及加密逻辑

> https://s2.loli.net/2023/10/26/v4LwkQInodD5lyZ.png

> https://s2.loli.net/2023/10/26/PiNmGJOy8RpeQ9S.png

### 描述所需要的功能

希望能添加对该接口的调用支持

**Comment by djkcyl** [comment]
这个接口目前是内测接口，可能是对不同账号和up有不同的灰度等级，应该是可以做的，晚点试试。

**Comment by djkcyl** [comment]
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/59153990/395f3196-d2ec-4ee8-b64e-c4791864b237)

测试了下，可以直接用，接口没有鉴权
