### ISSUE TITLE
直播样式及查动态的推荐

### ISSUE THREAD

**Issue by lin6953** [Well2333/nonebot-plugin-bilichat#125]
### 希望能解决的问题

带链接的通知样式似乎会增加风控几率，可否增加纯截图版的推送样式

### 描述所需要的功能

希望添加小程序样式的开播通知
查动态希望增加理解（如果动态为视频动态，则返回视频短链，不是视频类型则照原样返回截图）

**Comment by Well2333** [comment]
1. **bilichat_basic_info_url** 可以开关推送是否可以发送链接
2. 由于目前存货的 onebot11 协议库均不支持小程序，因此无法支持
3. 此功能不会添加，查动态应当返回的就是动态自身的链接
