### ISSUE TITLE
Bug: playwright版本异常导致出现问题

### ISSUE THREAD

**Issue by EvolvedGhost** [Well2333/nonebot-plugin-bilichat#139]
### 操作系统

Windows

### Python 版本

尝试过3.10和3.11

### NoneBot 版本

2.1.2

### Bilichat 版本

4.11.2

### 描述问题

这里写的playwright为>=1.17.2
https://github.com/Well2333/nonebot-plugin-bilichat/blob/8f76236222031d03047720884baa9100285bafdc/pdm.lock#L1386-L1395

这里写的playwright为1.36.0
https://github.com/Well2333/nonebot-plugin-bilichat/blob/8f76236222031d03047720884baa9100285bafdc/pdm.lock#L1626-L1644

实际安装会装上最新版1.40.0
https://pypi.org/project/playwright/

然后就会导致
`ModuleNotFoundError: No module named 'playwright._impl._api_types'`
然后插件不会响应任何事件

手动回到1.36版本后正常

查询可知在playwright 1.14.0中，新的导入方式为`playwright._impl._errors.Error`而不是`playwright._impl._api_types.Error`
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/92856393/3cefe06a-4ed6-43a9-a245-366ce751f4a9)

希望以后能把依赖版本号写死吧，不然版本问题之后会挺头疼

**Comment by Well2333** [comment]
fix #140

**Comment by Well2333** [comment]
版本写死不切实际，因为要考虑到与其他插件的兼容性问题
