### ISSUE TITLE
请问qq端的nonebot到底怎么部署？

### ISSUE THREAD

**Issue by maxin9966** [Well2333/nonebot-plugin-bilichat#144]
### 操作系统

Windows

### Python 版本

3.10

### NoneBot 版本

lastest

### Bilichat 版本

lastest

### 描述问题

如题，我看逻辑似乎是在qq端接收smslogin消息，但是qq端如何接入？我之前使用过gocqhttp，但是对这块不太熟，我似乎没有在项目里找到qq端消息接收回调。
如果尚未接入QQ的话，我应该如何登录？能给个教程吗？

**Comment by maxin9966** [comment]
nb run之后，项目提示bili未登录，我该如何登录bili？

**Comment by Well2333** [comment]
项目支持 onebot v11, mirai, qq（频道）三种适配器，具体接入请看对应的适配器相关介绍，而不是在本插件中发布issue
