### ISSUE TITLE
Feature: 增加通过uid订阅up主

### ISSUE THREAD

**Issue by forchannot** [Well2333/nonebot-plugin-bilichat#148]
### 希望能解决的问题

增加通过uid订阅up主

### 描述所需要的功能
https://github.com/Well2333/nonebot-plugin-bilichat/blob/6ea3864a1c49372b99018c976db3313c587c3b27/nonebot_plugin_bilichat/lib/bilibili_request/restAPI.py#L69-L76

刚发现其实这个接口是可以通过keyword=uid:{uid}来传入uid进行查询

因为通过名称sub可能会有up主名字奇奇怪怪和一些特殊符号，可以考虑只保留uid绑定(限制isdigit)或者两者都兼容

**Comment by Well2333** [comment]
现在二者均会保留，第一遍会直接搜索，如果没有搜到而且是纯数字则会作为uid搜索第二遍
