### ISSUE TITLE
Feature: 希望添加一个登录多账号功能

### ISSUE THREAD

**Issue by lin6953** [Well2333/nonebot-plugin-bilichat#153]
### 希望能解决的问题

B站号临时冻结

### 描述所需要的功能

只登录一个B站号的情况下，关注过多，或多人开播会出现B站账号临时冻结的情况，希望添加多个B站账号进行轮询

**Comment by Well2333** [comment]
1. 对于登录相关的指令逻辑应该如何设计

目前的指令是针对单账号设计的，如果改为多账号将会涉及 登录、登出、查看已登录 等相关指令，操作不可避免的会变得繁琐

2. 此部分涉及较为敏感的数据，是否应该添加到WebUI中

因为涉及Cookies，如果整合到 WebUI 中则需禁止全量获取登录数据（例如仅可获取账号UID）

3. 对于多账号的均衡负载，应采用随机调度还是顺序调度

这个影响不大，随机调度极端情况下可能会出现单账号负载过重的情况

**Comment by lin6953** [comment]
> 1. 对于登录相关的指令逻辑应该如何设计
，登录，退出登录，查看已登录

> 改为多账号将会涉及 登录、登出、查看已登录 等相关指令，退出账号操作可在指令后面添加已登录的账号UID，如（退出登录12345678）
> 
> 2. 可应该添加到WebUI中
> 
> 3. 对于多账号的均衡负载，应采用随机调度
减少单账号多轮询的负担
>
