### ISSUE TITLE
Feature: 希望指令能添加个允许群管理和群主使用的配置

### ISSUE THREAD

**Issue by Decrabbityyy** [Well2333/nonebot-plugin-bilichat#178]
### 希望能解决的问题

希望指令能添加个允许群管理和群主使用的配置

### 描述所需要的功能

bot的主人不一定在bot所在群聊，群管理和群主可以使用指令会方便点

**Comment by Well2333** [comment]
关于添加平台特化权限比较麻烦，很容易堆屎山，因此我建议使用webui进行操作，不过也不是不能加

最近考虑重构跨平台适配，可能会引入类似的管理功能，您也可以稍作等待，但不会很快推出，如果急需此功能的话请按照review的内容修改一下pr，我将会发布一个小版本进行更新
