### ISSUE TITLE
Bug: 严重问题，tiktoken-async无法兼容Python 3.12

### ISSUE THREAD

**Issue by NAOLIU** [Well2333/nonebot-plugin-bilichat#180]
### 操作系统

Windows

### Python 版本

Python 3.12.2

### NoneBot 版本

最新

### Bilichat 版本

最新

### 描述问题

      To install, run `rustup component add rustc`
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken-async
Failed to build tiktoken-async
ERROR: Could not build wheels for tiktoken-async, which is required to install pyproject.toml-based projects

我网上搜索了一大圈，发现tiktoken最近才兼容Python 3.12，但tiktoken-async并不兼容3.12，只兼容3.11，就算下载了Rust来编译也无法正常工作，导致pip install nonebot-plugin-bilichat[all]往往卡在tiktoken-async那边无法正常运作

**Comment by Well2333** [comment]
会考虑将此仓库换回tiktoken本身

**Comment by Well2333** [comment]
#182
