### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by LoCCai** [Well2333/nonebot-plugin-bilichat#185]
### 操作系统

Linux

### Python 版本

3.9.10

### NoneBot 版本

2.1

### Bilichat 版本

2

### 描述问题

你好，项目中的字体组件已经无法连接，可以上传一下吗？
        src: url("https://fonts.bbot/?name=vanfont.ttf");
        src: url("https://fonts.bbot?name=HarmonyOS_Sans_SC_Medium.ttf");
        src: url("https://fonts.bbot/?name=nte.ttf");

**Comment by Well2333** [comment]
此功能依赖于 playwright 的 router，此处为虚拟地址而不是真实的url，字体在你第一次运行插件时会下载到 Local store 插件提供的 data 文件夹

**Comment by LoCCai** [comment]
我渲染时使用此字体的地方全部都是一个方框，请问如果不是这个还有什么原因可能引起

**Comment by LoCCai** [comment]
![07c0de4c011b5e66f50f84b926ae5fdd](https://github.com/Well2333/nonebot-plugin-bilichat/assets/105721394/bb78f3f5-6d80-4406-91aa-293a03bdfee2)

**Comment by LoCCai** [comment]
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/105721394/2d456342-3a8e-42d7-97b5-9a64ec8a80ad)
y有在这个位置找到字体，不知道为什么图片没有

**Comment by Well2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/105721394/315529174-2d456342-3a8e-42d7-97b5-9a64ec8a80ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDI0MTYsIm5iZiI6MTcxMTA0MjExNiwicGF0aCI6Ii8xMDU3MjEzOTQvMzE1NTI5MTc0LTJkNDU2MzQyLTNhOGUtNDJkNy05N2I1LTlhNjRlYzhhODBhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxNzI4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODc2MzJmMmIxNGFjZjUwYWM1M2JkYWY2OTFmMmQzNDY2NmNkYWYzODNlZjgzYjAzYmJmZmJlYTIwNTgyNGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MlVgFyhE9zcgR_NcrIYU0crmjJ-U43Mm-r9yTnOQ7NE) y有在这个位置找到字体，不知道为什么图片没有

是的，这个就是上图中未渲染出的字体，正常情况下不应该出现此现象，但是我发现你的其他文字也不是我指定的字体，可能是playwright的字体加载顺序出问题了，或者字体被覆盖或无法加载了，你可以尝试换台机器部署或重新部署，看看还会不会出现此问题

**Comment by LoCCai** [comment]
请问推荐的htmlrender和playwright版本是多少
