### ISSUE TITLE
想单独使用某个模块

### ISSUE THREAD

**Issue by HuaOfSun** [Well2333/nonebot-plugin-bilichat#19]
词云和总结看来在env配置行为可以进行使用与不使用，不过不知道“基本信息”的这块是否也可以单独启用与禁用，譬如我目前的需求是想单独使用ai的总结，但不出现视频解析信息和词云，词云可以禁用，但解析的基本信息不知道是否可以在env里填写配置禁用，麻烦大佬了😂

**Comment by Well2333** [comment]
![image](https://user-images.githubusercontent.com/40534114/232185328-58dae42a-54b0-4485-9856-53d74643d635.png)
目前正在优化总结的提示词，等下下个版本(1.4.x)就加上

**Comment by HuaOfSun** [comment]
> ![image](https://user-images.githubusercontent.com/40534114/232185328-58dae42a-54b0-4485-9856-53d74643d635.png) 目前正在优化总结的提示词，等下下个版本(1.4.x)就加上

好的明白了👌🏻辛苦了

**Comment by Well2333** [comment]
功能已添加，关闭方式请参考readme
