### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by Onimaimai** [Well2333/nonebot-plugin-bilichat#198]
### 操作系统

Windows

### Python 版本

3.10

### NoneBot 版本

2.2.0

### Bilichat 版本

5.6.0

### 描述问题

lib/fetch_dynamic.py与subscribe/dynamic.py产生循环导入问题

### 截图或日志

![b69c8f7b8edc562cfa08ea4ab5cf5548](https://github.com/Well2333/nonebot-plugin-bilichat/assets/93068569/6fdd21a0-aa5b-444a-a91a-36749702d315)

**Comment by Onimaimai** [comment]
添加文件被共享导入
https://github.com/Well2333/nonebot-plugin-bilichat/commit/e250ec15b0439893c90b72a4979b612364e70816
https://github.com/Well2333/nonebot-plugin-bilichat/commit/c8653f8c2214f396513be2e8b5d2d02874de6cb0
https://github.com/Well2333/nonebot-plugin-bilichat/commit/c0a386dd230eb01a82c5ffa1fe8c068b031d56b6

**Comment by Well2333** [comment]
问题无法复现，此处不应构成循环导入的条件，请提供更详细的运行环境，例如操作系统版本，具体的python版本等

**Comment by Well2333** [comment]
截图中的部分代码行号与5.6.0版本的行号并不一致，如果您修改过代码，请把相关的修改一并提供
