### ISSUE TITLE
大佬能增加一个下播通知吗

### ISSUE THREAD

**Issue by SevenNine233** [Well2333/nonebot-plugin-bilichat#205]
### 希望能解决的问题

大佬能增加一个下播通知吗

### 描述所需要的功能

![6902f696-7834-46ab-9c3c-861c61639dfd](https://github.com/Well2333/nonebot-plugin-bilichat/assets/68588725/71cae982-a7ba-41d0-b69f-8df69dfb44c4)
类似这样的

**Comment by tutunewbee** [comment]
> ### 希望能解决问题
> 大佬能增加一个下播通知吗
> 
> ### 描述所需要的功能
> ![6902f696-7834-46ab-9c3c-861c61639dfd](https://private-user-images.githubusercontent.com/68588725/326847356-71cae982-a7ba-41d0-b69f-8df69dfb44c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTUwMDksIm5iZiI6MTcxNDQ5NDcwOSwicGF0aCI6Ii82ODU4ODcyNS8zMjY4NDczNTYtNzFjYWU5ODItYTdiYS00MWQwLWI2OWYtOGRmNjlkZmI0NGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE2MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjU1MmExMDhmZTFmY2RiOGU0ZDkxZDhhY2ZhMTMwMWUzYzYzY2Q0MjZkYWZkNWNkNDMxMjY2ZjVmODc2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C5pYBY17bs7suRbZ0whal_LDUDGRDrVgWns36B8o4hw) 类似这样的

**Comment by Well2333** [comment]
本来就有这个功能...
