### ISSUE TITLE
Bug: 安装插件之后程序无法正常退出？

### ISSUE THREAD

**Issue by LingLambda** [Well2333/nonebot-plugin-bilichat#221]
### 操作系统

Linux

### Python 版本

3.11.9

### NoneBot 版本

2.3

### Bilichat 版本

5.10.2

### 描述问题

安装插件后，按ctrl+v结束程序时程序卡死无法退出,必须关闭终端,卸载插件后恢复正常

### 截图或日志

(nonebot2) ling@ling-Ubuntu:~/公共的/nonebot2/lingbot2$ nb run
05-19 17:45:38 [SUCCESS] nonebot | NoneBot is initializing...
05-19 17:45:38 [INFO] nonebot | Current Env: dev
05-19 17:45:38 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {**'}, 'nickname': set(), 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'ps_only_su': 'True', 'duel': {'nickname': '嘎哒哒'}, 'ffmpeg': '/usr/bin/ffmpeg', 'pixiv_r18': 'False', 'search_limit': 2, 'record_priority': 99, 'saucenao_api_key': 'c289aa0c8ee0d3ce65e46e5f26f7031c1c9f9284', 'search_keyword': '图搜图'}
05-19 17:45:38 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
05-19 17:45:38 [DEBUG] nonebot | Succeeded to load adapter "Console"
05-19 17:45:38 [ERROR] nonebot | Failed to import "nonebot_plugin_picsearcher"
Traceback (most recent call last):
  File "/home/ling/公共的/nonebot2/lingbot2/bot.py", line 14, in <module>
    nonebot.load_plugin('nonebot_plugin_picsearcher')
  File "/home/ling/anaconda3/envs/nonebot2/lib/python3.11/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ling/anaconda3/envs/nonebot2/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/home/ling/anaconda3/envs/nonebot2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_picsearcher'
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_simplemusic" from "lingbot2.plugins.nonebot_plugin_simplemusic"
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
05-19 17:45:38 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
05-19 17:45:39 [WARNING] nonebot_plugin_memes | 表情列表解析失败，将重新生成
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_duel" from "lingbot2.plugins.nonebot_plugin_duel"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot-plugin-mcpic-main" from "lingbot2.plugins.nonebot-plugin-mcpic-main"
05-19 17:45:39 [INFO] nonebot_plugin_bilichat | nonebot_plugin_bilichat 缓存文件夹 ->  /home/ling/.cache/nonebot2/nonebot_plugin_bilichat
05-19 17:45:39 [INFO] nonebot_plugin_bilichat | nonebot_plugin_bilichat 数据文件夹 ->  /home/ling/.local/share/nonebot2/nonebot_plugin_bilichat
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
05-19 17:45:39 [INFO] nonebot_plugin_bilichat | bilichat_use_browser 所需依赖已安装，采用浏览器渲染模式
05-19 17:45:39 [INFO] nonebot_plugin_bilichat | bilichat_cache_serive 无法使用 MongoDB 作为缓存服务, 使用 JSON 文件作为缓存服务
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_auto_bot_selector"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
05-19 17:45:39 [WARNING] nonebot_plugin_bilichat | sentry_sdk 未安装
05-19 17:45:39 [INFO] nonebot_plugin_bilichat | 使用 JSON 文件作为缓存服务
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Loading font: sarasa-mono-sc-semibold.ttf
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Font sarasa-mono-sc-semibold.ttf found in local
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Loading font: sarasa-mono-sc-bold.ttf
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Font sarasa-mono-sc-bold.ttf found in local
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Loading font: vanfont.ttf
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Font vanfont.ttf found in local
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Loading font: HarmonyOS_Sans_SC_Medium.ttf
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Font HarmonyOS_Sans_SC_Medium.ttf found in local
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Loading font: nte.ttf
05-19 17:45:39 [DEBUG] nonebot_plugin_bilichat | Font nte.ttf found in local
05-19 17:45:39 [SUCCESS] nonebot_plugin_bilichat | 
****************************************************************************************
*                                                                                      *
*    Setting Up BILICHAT WebUI at                                                      *
*                                                                                      *
*    http://127.0.0.1:8080/bilichat/                                                   *
*                                                                                      *
*    You can upgrade WebUI manualy at                                                  *
*                                                                                      *
*    http://127.0.0.1:8080/bilichat/webui                                              *
*                                                                                      *
*    WARNING: Bilichat WebUI is currently running on default path. Please consider     *
*    to use different path via adding config `bilichat_webui_path` in .env file.       *
*                                                                                      *
****************************************************************************************
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "关注"
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "关注"
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "订阅"
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "bilichat.sub"
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "bilichat.unsub"
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "退订"
05-19 17:45:39 [WARNING] nonebot | Duplicated prefix rule "取关"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_bilichat"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "YetAnotherPicSearch"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "jock" from "lingbot2.plugins.jock"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "chats" from "lingbot2.plugins.chats"
05-19 17:45:39 [SUCCESS] nonebot | Succeeded to load plugin "AI_voice" from "lingbot2.plugins.AI_voice"
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "weather" from "lingbot2.plugins.weather"
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_epicfree"
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector memory_stat
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector swap_stat
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector bots
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector process_status
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector disk_usage
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector disk_io
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector nonebot_run_time
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector system_run_time
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector nonebot_version
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector ps_version
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector time
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector python_version
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector system_name
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector cpu_brand
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector cpu_count_logical
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector cpu_count
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector cpu_percent
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector cpu_freq
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector network_io
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered collector network_connection
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered global jinja filter `format_cpu_freq`
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered global jinja filter `percent_to_color`
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered global jinja filter `auto_convert_unit`
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Registered global jinja filter `br`
05-19 17:45:40 [DEBUG] nonebot_plugin_picstatus | Loaded template default TemplateInfo(collectors={'cpu_brand', 'nonebot_run_time', 'cpu_percent', 'system_run_time', 'network_io', 'cpu_count_logical', 'memory_stat', 'nonebot_version', 'cpu_count', 'disk_io', 'swap_stat', 'system_name', 'python_version', 'ps_version', 'network_connection', 'process_status', 'time', 'bots', 'cpu_freq', 'disk_usage'}, config=TemplateConfig(ps_default_components=['header', 'cpu_mem', 'disk', 'network', 'process', 'footer'], ps_default_additional_css=[], ps_default_additional_script=[]), renderer=<function render at 0x76e8c87882c0>)
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picstatus" from "lingbot2.plugins.nonebot_plugin_picstatus"
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "img" from "lingbot2.plugins.img"
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_pixiv" from "lingbot2.plugins.nonebot_plugin_pixiv"
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
05-19 17:45:40 [SUCCESS] nonebot | Succeeded to load plugin "saylove" from "lingbot2.plugins.saylove"
05-19 17:45:40 [SUCCESS] nonebot | Running NoneBot...
05-19 17:45:40 [DEBUG] nonebot | Loaded adapters: OneBot V11, Console
05-19 17:45:40 [INFO] uvicorn | Started server process [37584]
05-19 17:45:40 [INFO] uvicorn | Waiting for application startup.
05-19 17:45:40 [INFO] nonebot_plugin_memes | 正在检查资源文件...
05-19 17:45:42 [SUCCESS] nonebot | Console unmounted.
05-19 17:45:42 [WARNING] nonebot | Press Ctrl-C for Application exit
05-19 17:45:42 [INFO] nonebot_plugin_auto_bot_selector | pop bot Bot(type='Console', self_id='console')
05-19 17:45:42 [INFO] nonebot_plugin_bilichat | 重新检查可推送的用户
05-19 17:45:42 [INFO] nonebot_plugin_bilichat | 正在刷新激活的UP列表
05-19 17:45:42 [DEBUG] nonebot_plugin_bilichat | 正在尝试激活用户 QQ Group-_-1149228175 订阅的 UP
05-19 17:45:42 [DEBUG] nonebot_plugin_bilichat | 用户 QQ Group-_-1149228175 无可用推送 Bot
05-19 17:45:42 [DEBUG] nonebot_plugin_bilichat | 正在尝试激活用户 QQ Group-_-317701038 订阅的 UP
05-19 17:45:42 [DEBUG] nonebot_plugin_bilichat | 用户 QQ Group-_-317701038 无可用推送 Bot
05-19 17:45:42 [DEBUG] nonebot_plugin_bilichat | 已激活的UP:
无已激活的UP
05-19 17:45:42 [INFO] nonebot_plugin_bilichat | 检查可推送的用户完成
^C05-19 17:45:42 [INFO] uvicorn | Shutting down
05-19 17:45:42 [INFO] uvicorn | Waiting for application shutdown.
05-19 17:45:42 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
05-19 17:45:42 [INFO] nonebot_plugin_apscheduler | Scheduler Shutdown
05-19 17:45:42 [DEBUG] nonebot | Waiting for running bot connection hooks...
05-19 17:45:45 [DEBUG] meme_generator | Available resource urls: ['https://raw.githubusercontent.com/MeetWq/meme-generator/', 'https://fastly.jsdelivr.net/gh/MeetWq/meme-generator@', 'https://raw.gitmirror.com/MeetWq/meme-generator/'
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/101567686/c439889c-7c2d-4570-9990-ffb915a6f2d7)
]

**Comment by Well2333** [comment]
此问题我也经常触发，原因不明，有可能是uvicron、apscheduler或playwright导致的，而且触发条件不明。
个人在其他其他使用了uvicron的项目中也遇到了类似的问题，个人认为可能是uvicron导致的。
总而言之，此问题暂时没有解决方法，在遇到此问题时可以使用sigkill强制结束此进程。

**Comment by zifox666** [comment]
上游插件[htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender/)导致的
可以访问https://github.com/kexue-z/nonebot-plugin-htmlrender/pull/65 查看

**Comment by Well2333** [comment]
此问题似乎已得到解决，如果再次出现的话再打开这个 issue 吧
