### ISSUE TITLE
Bug: 发送检测到的动态和直播通知时报错

### ISSUE THREAD

**Issue by q921195075** [Well2333/nonebot-plugin-bilichat#223]
### 操作系统

Windows

### Python 版本

3.11.1

### NoneBot 版本

2.3.1

### Bilichat 版本

5.10.2

### 描述问题

发送检测到的动态时报错，包括动态和直播都会报错 但是在bilichat中加入一个模块，这个模块中使用nb本身的接口去send一个字符串或者图片是可以发送的

### 插件的配置项

# 对同一视频的响应冷却时间(防止刷屏)
bilichat_cd_time = 120
# 网络请求重试次数
bilichat_neterror_retry = 3
# 是否使用浏览器截图(需要额外依赖)
bilichat_use_browser = True

# 是否开启词云(需要额外依赖)
bilichat_word_cloud = True

# === AI 总结相关 ===
# 官方总结接口
bilichat_official_summary = False
# openai 接口(需要额外依赖)
# bilichat_openai_token = sk-xxxxxxx
# 网络代理
# bilichat_openai_proxy = "http://127.0.0.1:7890/"

COMMAND_SEP=[""]
COMMAND_START=[""]

# 命令的起始词，可设置为空
bilichat_cmd_start = ""

# 是否拦截事件(防止其他插件二次解析)
bilichat_block = True

# webui使用路径
bilichat_webui_path = "bilichat"
# bilichat_webui_path = ""

bilichat_cache_serive = "json"

bilichat_only_to_me = True

PORT=5963

### 截图或日志

![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/73765190/2d41aa95-a18d-4eba-8100-388dc45458bd)

**Comment by Well2333** [comment]
无法理解问题，请更清晰的描述问题触发的条件以及问题触发的现象
另外请提供plugin-alconna的版本号

**Comment by q921195075** [comment]
> 无法理解问题，请更清晰的描述问题触发的条件以及问题触发的现象 另外请提供plugin-alconna的版本号

我在运行之后，使用其他阿b账号测试发送动态和上下播，在bot检测到文字动态和开播动态之后，会正常截图，检测到下播之后也会调用发送命令，但是这两种情况，在调用发送命令时会报错，具体报错如问题中的图，整个报错都在截图中。下图为测试的发布文字动态时的报错截图，后续报错和问题中截图相同，受限于屏幕分辨率，只能截一部分：
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/73765190/700476e4-d805-47dd-995c-91111b77e837)

这是我在修改了这一部分后的输出，修改的subscribe/manager.py部分如下：
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/73765190/4c2129e5-af1d-4ece-ba83-dea52a4dfdf0)

输出如下：
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/73765190/03509006-74e0-4d95-afe8-eb3668c0f820)

我在commons模块中，添加了一个复读模块，在检测到两句相同的话之后会调用nonebot.adapters.onebot.v11.Bot.send_group_msg()函数去发送消息，这个发送是正常的。（如下图）
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/73765190/a4dff9b6-18fb-4544-a184-316379384164)

plugin-alconna版本号：0.46.2（如下图）
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/73765190/5341b87b-c373-48ae-a80d-d75b852587bd)
