### ISSUE TITLE
Bug: 动态查询出现异常

### ISSUE THREAD

**Issue by DreamGallery** [Well2333/nonebot-plugin-bilichat#227]
### 操作系统

Linux

### Python 版本

3.12

### NoneBot 版本

2.0

### Bilichat 版本

latest

### 描述问题

不知道为什么其他用到的功能都挺正常的，就是动态查询会出问题，返回一个错误信息-352, 尝试改过代码，但是没有其他具体的任何信息了，不清楚是哪里出了问题，已经扫码登录获取了cookie

### 截图或日志

```
[Dynamic] 开始获取动态...
[Dynamic] 使用 RestAPI 获取 XXXXXXXX | offset=950294383888957494
[Dynamic] 获取 XXXXXXXX 失败: [-352] -352
[Dynamic] 获取 XXXXXXXX 失败, skip...
[Dynamic] 获取完成
```
日志都是这样的，检测直播状态没问题的样子

**Comment by DreamGallery** [comment]
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/49429799/19295f9f-9488-4807-9a00-7dd902556cd6)
另外似乎专栏如果不是以文字开头会报错？搜了一下的确没有找到`//div[@id="read-article-holder"]`，不过不是很懂前端

**Comment by Well2333** [comment]
-352 是B站云端风控，此问题暂时无法解决。专栏的问题请单开一个issue并且附带详细的信息，例如专栏ID
