### ISSUE TITLE
Bug: 专栏解析 API 调用出错：list index out of range

### ISSUE THREAD

**Issue by DreamGallery** [Well2333/nonebot-plugin-bilichat#228]
### 操作系统

Windows

### Python 版本

3.12

### NoneBot 版本

2.0

### Bilichat 版本

latest

### 描述问题

随便找了几个专栏试了一下，似乎就是专栏开头是文字的可以解析，但是开头是图片的解析不了
这个就是不行的
https://www.bilibili.com/read/cv35721905/
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/49429799/dce3df41-95a5-48e6-ac11-34c091cddad9)
这个可以
https://www.bilibili.com/read/cv34697133/
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/49429799/4e9ab73e-0f3f-4a03-acef-2b140dd02e85)

不行的F12看网页的确是搜不到这个`//div[@id="read-article-holder"]`

**Comment by Well2333** [comment]
无法稳定复现，考虑是网络波动导致页面未能完全加载，或云端风控？

**Comment by DreamGallery** [comment]
> 无法稳定复现，考虑是网络波动导致页面未能完全加载，或云端风控？

我试过挺多次开头是图片的专栏好像就是不行，然后直接F12查看网页元素没有//div[@id="read-article-holder"]

**Comment by DreamGallery** [comment]
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/49429799/386788e9-ea1e-4ebd-b316-efe2e598ce7c)
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/49429799/32697d38-07a8-4408-b385-efefd30ad2fd)

**Comment by Well2333** [comment]
> > 无法稳定复现，考虑是网络波动导致页面未能完全加载，或云端风控？
> 
> 我试过挺多次开头是图片的专栏好像就是不行，然后直接F12查看网页元素没有//div[@id="read-article-holder"]

我这里怎么刷新都是有的，而且使用 inprivate 模式也能稳定存在，尝试修改为移动端 edge 的 UI 也可稳定存在

**Comment by Well2333** [comment]
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/40534114/8ffa0899-c759-4413-b075-f8da13b942bc)

**Comment by DreamGallery** [comment]
> ![image](https://private-user-images.githubusercontent.com/40534114/346561775-8ffa0899-c759-4413-b075-f8da13b942bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDIwNjYsIm5iZiI6MTcyMDQ0MTc2NiwicGF0aCI6Ii80MDUzNDExNC8zNDY1NjE3NzUtOGZmYTA4OTktYzc1OS00NDEzLWIwNzUtZjhkYTEzYjk0MmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyMjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzhhZjU4YmFhYTRlYTY0NmNhNjlkNTViZGM3MWRjODRiNjBiMDU2ZGVjMjZmYTU3ZjRlNTQzMjA1YjZjOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EFY4bJ8XPin_elAhLpbXsUe8zGmv-z3WlWI7MnJJAno)

这个是正常的，不正常的是开头是图片的
https://www.bilibili.com/read/cv35721905
试过几个其他的也是一样
比如这个开头是图片也是不行的
https://www.bilibili.com/read/cv35967927

**Comment by Well2333** [comment]
已复现，read-article-holder 部分的代码是为了提取专栏内的文字信息以用于AI总结和缓存，但对于没有文字的专栏此部分可以直接跳过。
此问题将在下个版本修复。

**Comment by DreamGallery** [comment]
> 已复现，read-article-holder 部分的代码是为了提取专栏内的文字信息以用于AI总结和缓存，但对于没有文字的专栏此部分可以直接跳过。 此问题将在下个版本修复。

辛苦了，有些专栏的文字是会出现在最后的，这点也要稍微考虑下

**Comment by Well2333** [comment]
> > 已复现，read-article-holder 部分的代码是为了提取专栏内的文字信息以用于AI总结和缓存，但对于没有文字的专栏此部分可以直接跳过。 此问题将在下个版本修复。
> 
> 辛苦了，有些专栏的文字是会出现在最后的，这点也要稍微考虑下

此问题无需考虑，因为搜索是根据 id 进行检索，类似 ctrl f ，因此顺序没有任何影响

**Comment by DreamGallery** [comment]
> 此问题无需考虑，因为搜索是根据 id 进行检索，类似 ctrl f ，因此顺序没有任何影响

就像我之前说的，文字不是在开头出现的就没有read-article-holder，如果后面的文字使用其他xpath去匹配的那没问题了
