### ISSUE TITLE
风控导致的获取动态失败(code -352)

### ISSUE THREAD

**Issue by YotoriGit** [Well2333/nonebot-plugin-bilichat#230]
### 操作系统

Windows

### Python 版本

3.1.1.8

### NoneBot 版本

2.3

### Bilichat 版本

5.10.4

### 描述问题

使用/查看动态时报错，没有返回消息
![QQ截图20240714175003](https://github.com/user-attachments/assets/810e6537-32cb-4685-b5f5-4cdcc26c3683)

### 插件的配置项

# 对同一视频的响应冷却时间(防止刷屏)
bilichat_cd_time=120
# 网络请求重试次数
bilichat_neterror_retry=3
# 是否使用浏览器截图(需要额外依赖)
bilichat_use_browser=True

bilichat_basic_info=True	#是否开启视频基本信息
bilichat_basic_info_style=Auto	#视频详情的图片样式，可用样式见下方备注
bilichat_basic_info_url=True	#开启视频进本信息的情况下，是否一同回复一个链接
bilichat_reply_to_basic_info=True	#后续消息是否回复基础信息(关闭则回复发送者的信息)
bilichat_dynamic=True	#是否开启动态解析
bilichat_dynamic_style=Auto	#动态详情的图片样式，可用样式见下方备注
bilichat_only_to_me=False

### 截图或日志

![QQ截图20240714175003](https://github.com/user-attachments/assets/c0ec3a08-939e-4b44-a2cf-779fcdd8a05a)

**Comment by Well2333** [comment]
此问题类似的问题已发现，由于b站风控规则改变导致的无法访问up主的主页，暂无已知的解决方案。
目前正在尝试绕过风控源，请等待版本更新。

**Comment by YotoriGit** [comment]
好吧。。。谢谢大佬的解答

**Comment by Lover-v** [comment]
去别的推送项目上翻了一下看到了这个，看看能不能参考一下。https://github.com/SocialSisterYi/bilibili-API-collect/issues/686#issuecomment-1884325027

**Comment by YotoriGit** [comment]
请问大佬什么时候有空可以更新吗，我也不懂这个啊。。。。

**Comment by Well2333** [comment]
目前已观测到的问题仅有动态抓取，直播和解析部分暂时没有问题。
现在用的请求库（bilireq）由于原作者也早就放弃维护了，现在出现了多方位的参数缺失，去测试每个缺失参数的含义、计算方法和有效时间的工作量过高了，修复需要花费大量时间，不光光是把上边那一个参数补齐就可以的。
由于我最近在准备考试没有时间写代码，因此建议先凑合用，等九月份开学了就有一点时间了。也欢迎有开发经验的大佬提供帮助。

**Comment by Well2333** [comment]
#233 已在 bilichat 中添加兼容 RSSHub 的 RSS 渠道动态获取方式，不过能稳定使用的 RSS 源就得靠各位八仙过海各显神通了
