### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by hakureireimusama** [Well2333/nonebot-plugin-bilichat#232]
### 操作系统

Windows

### Python 版本

3.10.11

### NoneBot 版本

2.3.2

### Bilichat 版本

5.11

### 描述问题

把Shamrock更新到了1.1.1，安卓QQ更新到了9.0.18（qq要求强制更新）。没出现了如下报错，之前是能正常推送开播下播通知的，现在QQ群不能推送了，现在没有主播开播或者下播，我稍后看看nb里面会不会有报错提示

### 插件的配置项

bilichat相关的配置项只写了这些
bilichat_block= True
bilichat_cd_time=300
bilichat_neterror_retry=5
bilichat_cache_serive=json
bilichat_command_to_me=False
bilichat_cmd_start=""

### 截图或日志

![image](https://github.com/user-attachments/assets/e4400f69-fd8f-4fbc-bb45-f559b12bb0e5)

**Comment by Well2333** [comment]
此问题很可能是shamrock造成的，而bilichat无法进行修复，因此issue可能无法由bilichat方面进行修复，您应该去对应的项目开发人员处进行咨询。
如果您认为此问题由bilichat或其上游依赖造成，请提供更详细的日志。
