### ISSUE TITLE
设置了rsshub地址，还是会报错，是不是我有什么设置错了？

### ISSUE THREAD

**Issue by hakureireimusama** [Well2333/nonebot-plugin-bilichat#249]
### 操作系统

Windows

### Python 版本

3.10.11

### NoneBot 版本

2.3.3

### Bilichat 版本

5.12.5

### 描述问题

设置了rsshub地址，还是会报错，是不是我有什么设置错了？

### 插件的配置项

bilichat_block = True 
bilichat_cd_time = 300
bilichat_neterror_retry = 5
bilichat_cache_serive = json
bilichat_command_to_me = False
bilichat_cmd_start = ""
bilichat_rss_base = "https://rsshub.atgw.io/"

### 截图或日志

![image](https://github.com/user-attachments/assets/0a9939b9-4925-4f32-b1ba-83b3b0b977b4)

**Comment by djkcyl** [comment]
您没有设置动态使用rss获取，仍在使用rest获取，请修改订阅的配置文件或通过webui修改，将其中的dynamic method 修改为 rss 即可。

注：当前webui可视化配置暂未能适配最新版bilichat，请直接修改左侧代码块中对应内容即可

**Comment by hakureireimusama** [comment]
![image](https://github.com/user-attachments/assets/346cb147-7e24-4114-9107-389ac3fa41be)
dynamic method 改为 rss 会报错这样的，用浏览器访问的话，是正常的

**Comment by Well2333** [comment]
无法确定问题原因，这看起来与bilichat无关，请检查您的rsshub服务是否正常运行，若正常运行则检查您的 rss_base 链接是否正确填写，或此问题是否反复出现？

**Comment by hakureireimusama** [comment]
![image](https://github.com/user-attachments/assets/76600dc7-326f-4c8e-b6db-26d7839eab11)
![image](https://github.com/user-attachments/assets/9721a110-27d9-4e61-b193-4f07a5a75f14)
![image](https://github.com/user-attachments/assets/0b84e9a7-7098-4887-8213-850fceb06791)
docker后台能看到有访问，我自己用edge访问这些网址也能访问，看到的返回值都是200（有几个503的是他们没发过动态），但是nb这边就显示获取失败，主动获取的错误也基本上是502或者503

**Comment by hakureireimusama** [comment]
可能是Windows sever的原因，我设置了防火墙的进出站规则，允许1200端口进出站，目前正常了
