### ISSUE TITLE
有些人开播的时候还会发一条动态，希望可以不发动态的开播通知

### ISSUE THREAD

**Issue by hakureireimusama** [Well2333/nonebot-plugin-bilichat#250]
### 希望能解决的问题

![image](https://github.com/user-attachments/assets/653c3a3e-5d74-41eb-9a8e-31032f3052f4)
有些人开播的时候还会发一条动态

### 描述所需要的功能

希望可以不发动态的开播通知

**Comment by hakureireimusama** [comment]
或者添加一个开关，可以选择是否发布开播动态推送，其他动态推送正常通知

**Comment by Well2333** [comment]
正常情况下，动态的直播通知是不会发送的，这可能是新添加rsshub动态获取导致的bug

**Comment by Well2333** [comment]
fixed #255
