### ISSUE TITLE
Bug: 无法加载插件

### ISSUE THREAD

**Issue by hakureireimusama** [Well2333/nonebot-plugin-bilichat#265]
### 操作系统

Windows

### Python 版本

3.10.11

### NoneBot 版本

2.4.0

### Bilichat 版本

5.13.4

### 描述问题

无法启动报错无法加载插件

### 插件的配置项

DRIVER=~fastapi+~httpx+~websockets
HOST=192.168.0.254
PORT=10244
nickname=["小小梦"]
SECRET=
ACCESS_TOKEN=
SUPERUSERS=["1317645806"]
COMMAND_START=[""]
bilichat_block=True
bilichat_cd_time=300
bilichat_cache_serive=json
bilichat_command_to_me=False
bilichat_cmd_start=""
bilichat_browser_shot_quality=65
bilichat_dynamic=False
bilichat_rss_base="http://192.168.0.3:1200/"

### 截图或日志

[logo.txt](https://github.com/user-attachments/files/17963961/logo.txt)

**Comment by Well2333** [comment]
此问题可能是 httpx 版本过低导致的，请升级 httpx 为最新版。

**Comment by hakureireimusama** [comment]
找到原因了，应该是因为httpx版本太高了，我的版本是0.28.0，我降级倒0.24.0之后可以正常运行了
