### ISSUE TITLE
视频字幕获取失败: BCut-ASR conversion failed due to network error

### ISSUE THREAD

**Issue by xi-yue-233** [Well2333/nonebot-plugin-bilichat#39]
一直都是except httpx.ReadTimeout,挑了重试次数也没用

**Comment by djkcyl** [comment]
字面意思，可能你服务器ip被b站屏蔽了或者你服务器本来就访问不了，或者你服务器上行带宽太少导致上传太慢然后超时

**Comment by xi-yue-233** [comment]
> 字面意思，可能你服务器ip被b站屏蔽了或者你服务器本来就访问不了，或者你服务器上行带宽太少导致上传太慢然后超时

提示upload success了，但是还是会抛出异常

**Comment by djkcyl** [comment]
可以给一下完整的报错吗

**Comment by xi-yue-233** [comment]
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/58218656/b841622d-ae99-49aa-b6a7-6b664103fbaf)
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/58218656/b437aa0f-b93b-406a-800e-ebc011802506)
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/58218656/1b0ef2a7-2e43-4f65-ac7e-c5fe6c7a3126)

**Comment by xi-yue-233** [comment]
目前是如果遇到过长的视频，会解析失败，可不可以设置一下httpx的超时时间？

**Comment by Well2333** [comment]
你这图截得和艺术品一样，前后顺序我都不知道是怎么回事，我只能猜着来
首先，最后一张图的 ERROR 只是说这次上传失败了，还能接着重试，不会导致图一的报错
然后，一个切片不光有上传，你获取字幕的时候炸了也会报这个错

**Comment by Well2333** [comment]
> 目前是如果遇到过长的视频，会解析失败，可不可以设置一下httpx的超时时间？

和超时时间没关系，超时是断开连接后限定时间内没有重连的时间，和你超长视频没关系，你超时时间设置一小时该炸还是炸

**Comment by xi-yue-233** [comment]
> > 目前是如果遇到过长的视频，会解析失败，可不可以设置一下httpx的超时时间？
> 
> 和超时时间没关系，超时是断开连接后限定时间内没有重连的时间，和你超长视频没关系，你超时时间设置一小时该炸还是炸

时间比较短的视频就可以解析成功，我尝试了一个3分钟的视频就成功了，但是一个12分钟的视频就会提示httpx.ReadTimeout

**Comment by Well2333** [comment]
> > > 目前是如果遇到过长的视频，会解析失败，可不可以设置一下httpx的超时时间？
> > 
> > 
> > 和超时时间没关系，超时是断开连接后限定时间内没有重连的时间，和你超长视频没关系，你超时时间设置一小时该炸还是炸
> 
> 时间比较短的视频就可以解析成功，我尝试了一个3分钟的视频就成功了，但是一个12分钟的视频就会提示httpx.ReadTimeout

我已经说明了，你长视频上传失败和超时时间没关系，长视频本来就容易上传失败，根据你网络状况也有关系，你就算把超时时间设置成一小时，你网不行也会炸

**Comment by xi-yue-233** [comment]
我将bcut_asr.py中的
`self.session = httpx.AsyncClient()`
添加了两个参数，变成
`self.session = httpx.AsyncClient(verify=False, timeout=None)`
对于一些长视频的字幕也可以进行解析了
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/58218656/f2ada164-14fb-465e-ad2f-0e3f6d81012b)
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/58218656/9f80f426-c96f-4473-9bc5-ac9ad1235913)
原来是这样的：
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/58218656/655adb86-e845-4f7c-b9a7-374a1fede28e)
