### ISSUE TITLE
大佬，能新增加合并转发消息么

### ISSUE THREAD

**Issue by lintonxue00** [Well2333/nonebot-plugin-bilichat#4]
全部发出来容易刷屏，合并消息比较美观好看

**Comment by djkcyl** [comment]
会做的

**Comment by Well2333** [comment]
> 全部发出来容易刷屏，合并消息比较美观好看

我正在考虑将全部信息写到一张图片里面，这样跨平台适配会轻松一些，而且也避免刷屏了。

不过要稍微等一段时间，因为设计绘图模板还是有些困难的。

如果有好的参考欢迎联系我们。

**Comment by Well2333** [comment]
目前关于这个 all in one 的设计陷入了瓶颈

展示一下废案：

![image](https://user-images.githubusercontent.com/40534114/230733317-42d23a1d-0656-4790-95c9-522503cb26c6.png)

这个方案虽然同时考虑了横竖屏的用户，但是由于视频简介和AI总结的长度不可控，因此可能会造成十分严重的左右信息失衡，因此目前暂时放弃双列设计了。

目前的改进方向是放弃词云，并对原有的简介进行精简设计后加入AI总结部分，草案如下：

![image](https://user-images.githubusercontent.com/40534114/230733562-29594962-2db8-4497-b58f-ed3e2bef46d1.png)

不过这也可能造成图片过长，在总结有意义的情况下，一个屏幕基本放不下，而且完全放弃了横屏用户的体验，不过相对左右信息失控已经好多了。

目前如果有合适的设计欢迎参与讨论

**Comment by Well2333** [comment]
![ee3b4a1acac69cee73e9b20098676bb1](https://user-images.githubusercontent.com/40534114/230759855-26273ec4-b076-482d-bdf3-683a763202e4.jpg)

由于仓库所有者坚持老的设计，一概不考虑新设计，新的设计计划封存，如果有哪个不怕死的佬愿意提供新的设计欢迎联系 @djkcyl 。

新的设计废案：

![image](https://user-images.githubusercontent.com/40534114/230759936-e50056a6-851d-4575-85ca-09d929cad5e6.png)

下个版本更新中将会添加合并转发消息，将词云和AI总结归入合并转发消息中。

**Comment by Well2333** [comment]
合并转发消息已经添加，在 .env 中添加如下配置即可
```
bilichat_forword_msg=["info","wordcloud","summary"] # 全部合并转发
bilichat_forword_msg=["wordcloud","summary"] # 合并转发词云和AI总结
bilichat_forword_msg=["info"] # 仅合并转发视频详情
```
注意，合并转发极易因为风控而失效，如果发现消息长时间未响应请注意观察控制台中的信息
