### ISSUE TITLE
wordcloud 插件不支持python3.11，建议修改 pyproject.toml 内的版本要求

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [Well2333/nonebot-plugin-bilichat#5]
https://github.com/amueller/word_cloud/issues/637
经过测试发现 wordcloud 插件最高支持到 python3.10

**Comment by Well2333** [comment]
目前考虑有两个选择：

~~1. 直接移除 bilichat 的 3.11 支持~~
2. 将词云功能作为可选依赖

~~目前个人更倾向于第二种，具体还是得看@djkcyl 的意见~~

目前经过讨论，决定将 wordcloud 作为可选依赖，不会移除 3.11 支持。
