### ISSUE TITLE
Invalid response status

### ISSUE THREAD

**Issue by TU-O0T** [Well2333/nonebot-plugin-bilichat#70]
建议加入自定义wss选项
参考隔壁spark-gpt
![image](https://github.com/Aunly/nonebot-plugin-bilichat/assets/110141765/ca4b691d-760e-48bf-a666-26add90cb994)

**Comment by TU-O0T** [comment]
报错如下
视频(专栏) av955913114 总结失败: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

**Comment by Well2333** [comment]
已新增配置项 bilichat_newbing_wss_link
