### ISSUE TITLE
[新功能] 添加配置项修改openai.api_base

### ISSUE THREAD

**Issue by xxtg666** [Well2333/nonebot-plugin-bilichat#74]
考虑到国内服务器挂代理有可能会出事，所以自己搭了一个openai api的镜像，可在国内访问的那种，希望插件能支持这样用
设置 `openai.api_base` 就可以实现

**Comment by xxtg666** [comment]
看了下代码，好像没有用openai官方库，等下我发个pr吧

**Comment by Well2333** [comment]
fix #75
