### ISSUE TITLE
[bug反馈]插件黑白名单没有校验user_id，channel_id

### ISSUE THREAD

**Issue by Cypas** [Well2333/nonebot-plugin-bilichat#76]
https://github.com/Aunly/nonebot-plugin-bilichat/blob/09bd3007d96fb6629633fa2bebf5c36c00a9e31b/nonebot_plugin_bilichat/__init__.py#L113-L115

这里直接返回的是配置项的是否允许私聊，并没有对user_id进行校验

https://github.com/Aunly/nonebot-plugin-bilichat/blob/09bd3007d96fb6629633fa2bebf5c36c00a9e31b/nonebot_plugin_bilichat/__init__.py#L124-L126

channel_id也是同上，这里进行二次校验的话，黑白名单也就不仅仅只对群生效，qq号和频道号也可以用于黑白名单

**Comment by Well2333** [comment]
这里原本就是这么设计的，对于私聊不会添加判断，不过这点也可以修改一下

**Comment by Well2333** [comment]
fix #80
