### ISSUE TITLE
bilichat_cache_serive的auto配置无法捕获No module named 'nonebot_plugin_mongodb'错误

### ISSUE THREAD

**Issue by forchannot** [Well2333/nonebot-plugin-bilichat#85]
升级到3.0（最新）版本后，如果不配置`bilichat_cache_serive=json`，保持默认的auto，会导致启动时抛出错误`ModuleNotFoundError: No module named 'nonebot_plugin_mongodb'`，观察发现程序成功进入了except内并且运行了`logger.info("bilichat_cache_serive can't use MongoDB as cache serive, using JsonFile")`，但是仍然会抛出该错误。在我使用的插件中仅有bilichat有mongodb的需求
![image](https://github.com/Well2333/nonebot-plugin-bilichat/assets/100580891/04ddbc4d-f68e-4891-9098-d7244194d03d)

**Comment by Well2333** [comment]
这是正常现象，你看下面的日志已经自动切换到 json 了，如果不是 Auto 就直接报错退出了，这里我把 log level 改成 warning 吧

**Comment by Well2333** [comment]
此日志为 nonebot 框架层面抛出，我这里无法修改，所以虽然难看但是只能这样了
